---
apiVersion: v1
kind: Service
metadata:
  name: testing4
  namespace: team1
  labels:
    app: testing4
    service: testing4
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: testing4